### ISSUE TITLE
Create storyboard for all registration views

### ISSUE THREAD

**Issue by tangziyi001** [new-dawn/new_dawn_ios_prod#13]

**Comment by tianchuxie** [comment]
![screen shot 2018-12-23 at 2 45 18 pm](https://user-images.githubusercontent.com/10569455/50387029-6c7b8580-06c1-11e9-8bd0-8461a1116c71.png)


This is the easiest way to generate the screens, I believe it would work. 
Please give a try and tell me how. 
Thank you

**Comment by tangziyi001** [comment]
Awesome. Could you merge your branch into playground repo’s master? So we can pull them down to make some changes

**Comment by tangziyi001** [comment]
You can merge your branch by opening a Pull request (PR) in github.
